version: '3.2'

services:
  rabbit:
      hostname: rabbit
      image: rabbitmq:latest
      environment:
          - RABBITMQ_DEFAULT_USER=admin
          - RABBITMQ_DEFAULT_PASS=mypass
      ports:
          - "5672:5672"
      networks:
          - cm-net
  api:
    build:
      context: ./api
      dockerfile: dockerfiles/api/Dockerfile
    expose:
          - 80
    restart: always
    external_links:
          - postgis-database:postgis

    links:
         - rabbit
         - redis
    depends_on:
      - redis
      - rabbit
    networks:
        - cm-net
        - backend
    volumes:
        - /home/iig/hotmaps/tmp:/var/tmp
        - /home/iig/hotmaps/repositories:/var/hotmaps/repositories

  redis:
    image: redis
    networks:
          - cm-net

#  to define a custem name for network, the version 3.5 of docker-compose is required(docker version 17.12.0+)
volumes:
  static-content:

networks:
  backend:
    driver: bridge
  cm-net:
    driver: bridge
